version: '3.8'
services:
  service-db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: vztv
      POSTGRES_PASSWORD: vztv
      PGPORT: "5431"
    ports:
      - "5431:5431"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped