spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: myclient
            client-secret: vkaOniwWbz7hfPVHqN3mcMpabUGrFwS6
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/myrealm
            user-name-attribute: preferred_username
            redirect-uti: http://localhost:8080
  application:
    name: studythumeleaf
  datasource:
    url: jdbc:postgresql://localhost:5431/vztv
    username: vztv
    password: vztv
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  use-forward-headers: true
  port: 8080
keycloak:
  server-url: http://localhost:9090/auth
  realm: myrealm
  username: admin
  password: admin