spring:
  application:
    name: studythumeleaf
  datasource:
    url: jdbc:postgresql://localhost:5431/vztv
    username: vztv
    password: vztv
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  use-forward-headers: true
  port: 8081